# Generated by Django 6.0.7 on 2026-07-25 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorden',
            name='variante',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='aplico_descuento_registro',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='agotado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='video',
        ),
        migrations.AddField(
            model_name='itemorden',
            name='imagen_seleccionada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.imagenproducto'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemorden',
            name='talla',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Validación'), ('CONFIRMADO', 'Confirmado (Listo para Pagar)'), ('RECHAZADO', 'Rechazado'), ('PAGADO', 'Pago Recibido'), ('ENVIADO', 'Pedido Enviado')], default='PENDIENTE', max_length=20),
        ),
        migrations.DeleteModel(
            name='VarianteProducto',
        ),
    ]
