# Generated by Django 6.0.7 on 2026-07-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_itemorden_variante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='color_nombre',
            field=models.CharField(blank=True, help_text='Ej: Cloud White / Core Black. Si defines un color, se mostrará como opción seleccionable.', max_length=100, null=True),
        ),
    ]
