# Generated by Django 6.0.7 on 2026-07-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_imagenproducto_color_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='color_nombre',
            field=models.CharField(blank=True, help_text='OPCIONAL: Nombre del color (ej: Verde, Negro). Llena esto SOLO si esta foto es la muestra de una variante de color en el panel derecho. Para fotos normales de la galería o ángulos, DÉJALO EN BLANCO.', max_length=100, null=True),
        ),
    ]
