# Generated by Django 6.0.7 on 2026-07-29 14:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_imagenproducto_color_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Imágenes de Productos'},
        ),
        migrations.AlterModelOptions(
            name='itemorden',
            options={'verbose_name': 'Ítem de Orden', 'verbose_name_plural': 'Ítems de Orden'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['nombre'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='resena',
            options={'ordering': ['-fecha'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en la galería.'),
        ),
        migrations.AddField(
            model_name='marca',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el producto se muestra en la tienda.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='es_principal',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='imagen_seleccionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.imagenproducto'),
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orden',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Validación'), ('CONFIRMADO', 'Confirmado (Listo para Pagar)'), ('RECHAZADO', 'Rechazado'), ('PAGADO', 'Pago Recibido'), ('ENVIADO', 'Pedido Enviado')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_regular',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
